# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3773b51ca59d230918d1c0c74950b2a4d3f50426da7001ba8e4cc7c1e38aef3da323fb9d68afb34d5eccb690810d85f0261200076b3b554d08fb0d25b7781d8f

test:
  secret_key_base: db82f5dbf61191cdeb13d633266ac553d8f91260b92ecc4454f5ccb5cd289571574ac78f7bf337ac3013863e7555cd71ea46fd25b2be0af0c87ec36a0f517e00

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
